import { Metadata } from 'next';

const title = 'Kanban App';
const description =
	'A full-stack invoice management application built with Next.js, featuring Google authentication, real-time database syncing, and PDF generation capabilities.';
export const url = 'https://kanban-app-iyke.vercel.app';

const keywords = [
	'kanban board app',
	'task management software',
	'project management tool',
	'drag and drop task manager',
	'kanban task tracker',
	'nextjs kanban board',
	'real-time task management',
	'nextjs task management',
	'convex real-time app',
	'clerk authentication app',
	'shadcn ui kanban',
	'tailwind kanban board',
	'react task manager',
	'typescript kanban app',
	'drag and drop kanban',
	'real-time collaboration tool',
	'subtask management',
	'multi-board task manager',
	'responsive kanban board',
	'dark mode task manager',
	'mobile-friendly kanban',
	'agile project management',
	'scrum board online',
	'team collaboration tool',
	'workflow management app',
	'productivity task tracker',
	'personal task organizer',
	'project planning software',
	'free kanban board with drag and drop',
	'real-time kanban task management',
	'nextjs fullstack project management',
	'customizable kanban columns',
	'kanban board with authentication',
	'collaborative task management app',
	'modern kanban board interface',
	'trello alternative',
	'jira alternative opensource',
	'asana alternative free',
	'notion kanban alternative',
	'clickup alternative',
	'fullstack nextjs project',
	'convex backend project',
	'react portfolio project',
	'nextjs convex example',
	'clerk nextjs integration',
	'dnd-kit implementation',
	'shadcn ui project example',
];

export const metaDataOptions: Metadata = {
	generator: 'Next.js',
	applicationName: 'Kanban App',
	referrer: 'origin-when-cross-origin',
	keywords,
	authors: [{ name: 'Kelvin Ochubili', url: 'https://twitter.com/iykekelvins' }],
	creator: 'Kelvin Ochubili',
	publisher: 'Kelvin Ochubili',
	formatDetection: {
		email: false,
		address: false,
		telephone: false,
	},
	openGraph: {
		title,
		description,
		url,
		siteName: 'Kanban App',
		images: [
			{
				url: '/opengraph-image.png',
				width: 800,
				height: 600,
			},
			{
				url: '/opengraph-image.png',
				width: 1800,
				height: 1600,
				alt: 'Kanban App',
			},
		],
		locale: 'en_US',
		type: 'website',
	},
	twitter: {
		card: 'summary_large_image',
		title,
		description,
		creator: '@iykekelvins',
		images: ['/opengraph-image.png'],
	},
	alternates: {
		canonical: '/',
	},
	robots: {
		index: true,
		follow: true,
		nocache: false,
		googleBot: {
			index: true,
			follow: true,
			noimageindex: false,
			'max-video-preview': -1,
			'max-image-preview': 'large',
			'max-snippet': -1,
		},
	},
};
